# ===============================
# Application Name
# ===============================
spring.application.name=demoRESTfullAPI
# ===============================
# Server Configuration
# ===============================
# Render sẽ tự động gán port động qua biến ${PORT}. Nếu không có (chạy ở máy tính), nó sẽ lấy port 8080.
server.port=${PORT:8080}
# ===============================
# Database Configuration (Railway)
# ===============================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# JPA / Hibernate
# ===============================
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.security=DEBUG
# ===============================
# JWT Configuration
# ===============================
# application.properties
jwt.secret=${JWT_SECRET:mySecretKeyForJWTToken123456789012345678901234567890}
jwt.expiration=86400000
# 86400000 milliseconds = 24 giờ
# 3600000 ms = 1 giờ
# 1800000 ms = 30 phút



